site_name: SpecJava
site_description: Lightweight Type-Like Hoare-Separation Specs for Java

repo_name: tvcsantos/specjava
repo_url: https://github.com/tvcsantos/specjava
edit_uri: blob/master/docs/

copyright: Copyright 2010 Tiago Santos

theme:
  name: material
  logo: img/icons8-java.svg

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - 'https://cdn.jsdelivr.net/npm/prismjs@1.28.0/themes/prism.css'
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-core.min.js'
  - 'https://cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-clike.min.js'
  - 'https://cdn.jsdelivr.net/npm/prismjs@1.28.0/components/prism-java.min.js'
  - 'https://cdn.jsdelivr.net/npm/prismjs@1.28.0/plugins/autoloader/prism-autoloader.min.js'
  - 'js/prism-specjava.js'
